/**
 * Exception for when there is no connection between the start- and end vertices.
 * @author Joey & Yusuf
 * @version 15.07.21
 */
public class NoPathException extends Exception {

	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 8360921557975360292L;

	public NoPathException() {
		
	}
	
	public NoPathException(String message) {
		super(message);	
	}
}
